config sublinkpro 'main'
	option enabled '0'
	option port '8000'
	option db_path '/etc/sublinkpro'
	option log_path '/var/log/sublinkpro'
	option log_level 'info'
	option expire_days '14'
	option web_base_path ''
	option captcha_mode '2'
	option login_fail_count '5'
	option login_fail_window '1'
	option login_ban_duration '10'
	option dsn ''
	option open_firewall '0'
