# SPDX-License-Identifier: GPL-3.0-only

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SublinkPro
LUCI_DEPENDS:=+sublinkpro
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-sublinkpro
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_LICENSE:=GPL-3.0-only
PKG_MAINTAINER:=XiaoHaiSly
PKG_PO_VERSION:=$(PKG_VERSION)-r$(PKG_RELEASE)

include $(TOPDIR)/feeds/luci/luci.mk

